### ISSUE TITLE
vendor/autoload.php file not found due to path error Laravel 11

### ISSUE THREAD

**Issue by chabid492** [omaralalwi/Gpdf#7]
**Error occurs when trying to install new font**

>php vendor/omaralalwi/gpdf/scripts/install_font.php "Arial" ./resources/fonts/ARIAL-Normal.ttf ./resources/fonts/ARIAL-Bold.ttf ./resources/fonts/ARIAL-Italic.ttf ./resources/fonts/ARIAL-BoldItalic.ttf

Warning: require_once(D:\laragon\www\InterPay\InterPayReceiptGenerator\vendor\omaralalwi\gpdf\scripts/../vendor/autoload.php): Failed to open stream: No such file or directory in D:\laragon\www\InterPay\InterPayReceiptGenerator\vendor\omaralalwi\gpdf\scripts\install_font.php on line 3

Fatal error: Uncaught Error: Failed opening required 'D:\laragon\www\InterPay\InterPayReceiptGenerator\vendor\omaralalwi\gpdf\scripts/../vendor/autoload.php' (include_path='.;D:/laragon/etc/php/pear') in D:\laragon\www\InterPay\InterPayReceiptGenerator\vendor\omaralalwi\gpdf\scripts\install_font.php:3
Stack trace:
#0 {main}
  thrown in D:\laragon\www\InterPay\InterPayReceiptGenerator\vendor\omaralalwi\gpdf\scripts\install_font.php on line 3
  
  
  It works for me when I have changed the script file code to 
  **File Path**: vendor\omaralalwi\gpdf\scripts\install_font.php
  
 **//require_once __DIR__ . '/../vendor/autoload.php';
require_once __DIR__ . '/../../../autoload.php';**

**Comment by chabid492** [comment]
@omaralalwi 
Can you please fix this problem

https://github.com/omaralalwi/Gpdf/issues/7#issue-2504709257

**Comment by omaralalwi** [comment]
ok i will check and let you know ASAP

**Comment by chabid492** [comment]
Thank you for your response

**Comment by omaralalwi** [comment]
Resolved Here https://github.com/omaralalwi/Gpdf/pull/8
please make sure to update to latest version (current 1.0.4)

**Comment by chabid492** [comment]
Thanks to fix it quickly, it worked.
